### PR TITLE
remove plunder-app

### PR DESCRIPTION
**Pull request by tuminoid**
Plunder-app has not been updated in 4 years. Remove it.

### CODE REVIEW

**Comment by alexellis** [comment]
Seems a bit aggressive?

**Comment by tuminoid** [comment]
> Seems a bit aggressive?

Well it states in the readme that projects must be active, have recent releases etc, but I guess 4 years is not inactive then.

**Comment by alexellis** [comment]
A little context would always be appreciated, so if you'd quoted that I would have merged the PR or have asked you to have moved it to the inactive section.

**Comment by tuminoid** [comment]
Sorry. I assumed the maintainer would either know what the rules are in their own repo, or asked for the context before closing the PR if it was unclear.  Let’s agree both could’ve done better.

**Pull request closed without merging**
