### PR TITLE
Adds Maxihost to Bare Metal Cloud list of providers.

### PR DESCRIPTION
**Pull request by esoubihe**
Please fill out the whole template. If you delete or ignore the template, the PR will be closed.

## Project name
[Maxihost Bare Metal Cloud](https://www.maxihost.com)

## Why do you feel this project should be added to awesome-baremetal?
Maxihost specialized exclusively on Bare Metal Cloud solutions. It supports multiple locations and has an API to automate both provisioning and management of nodes.

## What's your connection to the project?
Author

## Submission type
Bare Metal Cloud platform

## Has the project had commits within the last 6 months?
[Yes](https://www.maxihost.com/changelog)

### CODE REVIEW

**Comment by justinclift** [comment]
***\*cough*\*** Alphabetic ordering... ***\*cough*\*** :wink:

**Comment by alexellis** [comment]
Hey @esoubihe we'd like this PR

**Comment by alexellis** [comment]
Which of your two brands do you prefer currently? I added one that seemed to be listed on your profile.

Do you still have aarch64 hardware too?

**Comment by esoubihe** [comment]
Hey @alexellis, Maxihost rebranded to Latitude.sh last year. Since you just added us on c488b23, I guess this can remain closed.

**Comment by esoubihe** [comment]
> Do you still have aarch64 hardware too?

We do but only for [custom builds](https://www.latitude.sh/custom-deployments). 

It might be interesting to add a GPU label for providers that support them. Relevant to many use cases.

**Pull request closed without merging**
