### PR TITLE
remove razor

### PR DESCRIPTION
**Pull request by tuminoid**
Razor has been archived for almost 3 years. Remove it.

### CODE REVIEW

**Comment by alexellis** [comment]
The tone is very direct here, it sounds like you own and maintain this repo. Have you thought about asking in a more collaborative way?

Alex, this project has been archived what do you suggest?

I'd suggest moving it to a new sub-section (archived projects)

**Comment by tuminoid** [comment]
It is a PR, not an issue. PRs usually clearly state the reason for change and change itself. Which this PR does in order to keep curated list clean of projects that break the rules stated in readme.

What is not collaborating is closing the PR without discussion, and assuming a contributor would know you might plan a new sub-section that doesn’t yet exist. But you do you.

**Comment by alexellis** [comment]
I'm suggesting raising a new PR and implementing that solution. It's up to you if you want to do that. I assume it's in your interest to make Metal3 look more appealing more of an obvious choice.

**Comment by tuminoid** [comment]
I’m just a fan of well curated lists, they are handy. Yes, I found your repo because its relevant for me due working in similar project, but I have no need to push our FOSS like that.

As for two PRs: one was archived, other inactive, so I felt they didn’t belong to one commit. You could’ve asked me to put them in one instead of bluntly closing it.

Anyways, I see you implemented inactive list. Thanks for the cleanup.

**Comment by alexellis** [comment]
I did both @tuminoid - closed and asked you to put them into one, all within a short period of time.

**Pull request closed without merging**
