### PR TITLE
Add 2 projects

### PR DESCRIPTION
**Pull request by SuperQ**
Add Collins and Ganeti to the list.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi thanks for your interest. Can you say why you think both projects should be on the list?

**Comment by SuperQ** [comment]
Collins is extremely powerful inventory automation. You can use it to build a fully automated bare metal provisioning system. It was developed by Tumbler to automate their thousands of machines. We used it at SoundCloud to automate our bare metal. Because it's both a CMDB, and a state machine, you can develop full bare metal lifecycle management. For example, we could intake a rack of servers, get an inventory of their hardware, and put them in standby (IPMI off). When we need them, we could with a single click power them up, install a base OS, provision them with Chef, and put them into production. I did this for full database nodes as well. In the same sequence, I could de-provision them and put them back to an empty state with a single click.

Ganeti is one of the original "hyperconverged" VM management systems (2007). It was developed at Google to manage their corp hardware consolidation needs. They wanted to be able to deploy small office servers, without the overhead of having to deploy a SAN to a small site. It also was built to scale up, providing Linux-based VDI services on 1000 node clusters. All open source, built with free software components.

**Comment by alexellis** [comment]
Thank you for the backstory, the context is much appreciated.

Can you say whether either or both of the projects are actively used and developed?

**Comment by SuperQ** [comment]
Good question.

Both projects are in use in a number of places, development is slow, but both are "feature complete" projects. They are stable, reliable software. But both are flexible and extensible. And not garbage like OpenStack.

**Comment by ssgelm** [comment]
+1 to both of these being added. Collins (and its pxe server Genesis) are in active use at Tumblr along with at least a few other companies I am aware of. Ganeti is how the Debian project runs all of their VMs which, to me, is a pretty strong endorsement of relevance.

**Pull request merged**
