### PR TITLE
add varnish-cache

### PR DESCRIPTION
**Pull request by craig**

### CODE REVIEW

**Comment by alexellis** [comment]
Hi thanks for your interest. Can you say why you think this project should be on the list?

**Comment by craig** [comment]
Varnish Cache is a web application accelerator also known as a caching HTTP reverse proxy. You install it in front of any server that speaks HTTP and configure it to cache the contents. Varnish Cache is really, really fast. It typically speeds up delivery with a factor of 300 - 1000x, depending on your architecture. 

-> Varnish can replace proprietary network caching appliances. 

It's a reverse Caching Proxy just a LOT more modern and flexible than Squid by design.

**Comment by alexellis** [comment]
Thanks for the reply. Is this something that you've used with bare-metal specifically, or mainly adding as an alternative to squid? I've since updated the PR template, as I realise it wasn't clear what kind of info I was looking for about submissions.

**Comment by craig** [comment]
I'm currently using it on bare-metal - it's networking stuff and does not perform extremely in high-performance virtualized environments. If you only want tools that are bare-metal specific, haproxy and squid should be removed from the list, too.

**Comment by alexellis** [comment]
> If you only want tools that are bare-metal specific, haproxy and squid should be removed from the list, too.

Both HAProxy and Squid are used by the bare-metal provisioning solutions above, that's why they are here.

**Comment by alexellis** [comment]
This PR needs a rebase so I'll get this added manually

**Pull request closed without merging**
